-- CreateTable
CREATE TABLE "MobileFoodFacilityPermit" (
    "id" SERIAL NOT NULL,
    "locationid" INTEGER NOT NULL,
    "Applicant" TEXT NOT NULL,
    "FacilityType" TEXT NOT NULL,
    "cnn" INTEGER NOT NULL,
    "LocationDescription" TEXT NOT NULL,
    "Address" TEXT NOT NULL,
    "blocklot" TEXT NOT NULL,
    "block" TEXT NOT NULL,
    "lot" TEXT NOT NULL,
    "permit" TEXT NOT NULL,
    "Status" TEXT NOT NULL,
    "FoodItems" TEXT NOT NULL,
    "X" TEXT NOT NULL,
    "Y" TEXT NOT NULL,
    "Latitude" DOUBLE PRECISION NOT NULL,
    "Longitude" DOUBLE PRECISION NOT NULL,
    "Schedule" TEXT,
    "dayshours" TEXT,
    "NOISent" TEXT,
    "Approved" TEXT,
    "Received" TEXT,
    "PriorPermit" INTEGER NOT NULL,
    "ExpirationDate" TEXT NOT NULL,
    "Location" TEXT NOT NULL,
    "FirePreventionDistricts" INTEGER,
    "PoliceDistricts" INTEGER,
    "SupervisorDistricts" INTEGER,
    "ZipCodes" INTEGER,
    "NeighborhoodsOld" INTEGER,

    CONSTRAINT "MobileFoodFacilityPermit_pkey" PRIMARY KEY ("id")
);
