-- CreateTable
CREATE TABLE "MobileFoodFacilityPermit" (
    "locationid" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Applicant" TEXT NOT NULL,
    "FacilityType" TEXT NOT NULL,
    "cnn" INTEGER NOT NULL,
    "LocationDescription" TEXT NOT NULL,
    "Address" TEXT NOT NULL,
    "blocklot" TEXT NOT NULL,
    "block" TEXT NOT NULL,
    "lot" TEXT NOT NULL,
    "permit" TEXT NOT NULL,
    "Status" TEXT NOT NULL,
    "FoodItems" TEXT NOT NULL,
    "X" REAL NOT NULL,
    "Y" REAL NOT NULL,
    "Latitude" REAL NOT NULL,
    "Longitude" REAL NOT NULL,
    "Schedule" TEXT,
    "dayshours" TEXT,
    "NOISent" TEXT,
    "Approved" DATETIME NOT NULL,
    "Received" TEXT,
    "PriorPermit" INTEGER NOT NULL,
    "ExpirationDate" DATETIME NOT NULL,
    "Location" TEXT NOT NULL,
    "FirePreventionDistricts" INTEGER NOT NULL,
    "PoliceDistricts" INTEGER NOT NULL,
    "SupervisorDistricts" INTEGER NOT NULL,
    "ZipCodes" INTEGER NOT NULL,
    "NeighborhoodsOld" INTEGER NOT NULL
);
